-- Auto-generated by Matugen

require("base16-colorscheme").setup({
    base00 = "{{colors.surface_container_lowest.default.hex}}",
    base01 = "{{colors.surface_container.default.hex}}",
    base02 = "{{colors.surface_container_highest.default.hex}}",
    base03 = "{{colors.outline_variant.default.hex}}",
    base04 = "{{colors.on_surface_variant.default.hex}}",
    base05 = "{{colors.on_surface.default.hex}}",
    base06 = "{{colors.inverse_on_surface.default.hex}}",
    base07 = "{{colors.surface_bright.default.hex}}",

    base08 = "{{colors.primary.default.hex}}",
    base09 = "{{colors.error.default.hex}}",
    base0A = "{{colors.secondary.default.hex}}",
    base0B = "{{colors.outline.default.hex}}",
    base0C = "{{colors.tertiary_container.default.hex}}",
    base0D = "{{colors.primary_container.default.hex}}",
    base0E = "{{colors.secondary_fixed_dim.default.hex}}",
    base0F = "{{colors.error.default.hex | lighten: 5}}",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
    for _, v in pairs(groups) do
        vim.api.nvim_set_hl(0, v, value)
    end
end

set_hl_mutliple({ "TSFunction", "TSParameter" }, { link = "TSVariable" })
set_hl_mutliple({ "CursorLineSign", "CursorLineFold" }, { link = "CursorLine" })

vim.api.nvim_set_hl(0, "LineNr", { fg = "{{colors.outline.default.hex}}" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "{{colors.on_surface_variant.default.hex}}" })
