-- Auto-generated by Matugen
return {
    base00 = "{{colors.base00_source.default.hex}}",
    base01 = "{{colors.base01_source.default.hex}}",
    base02 = "{{colors.base02_source.default.hex}}",
    base03 = "{{colors.base03_source.default.hex}}",
    base04 = "{{colors.base04_source.default.hex}}",
    base05 = "{{colors.base05_source.default.hex}}",
    base06 = "{{colors.base06_source.default.hex}}",
    base07 = "{{colors.base07_source.default.hex}}",
    base08 = "{{colors.base08_source.default.hex}}",
    base09 = "{{colors.base09_source.default.hex}}",
    base0A = "{{colors.base0A_source.default.hex}}",
    base0B = "{{colors.base0B_source.default.hex}}",
    base0C = "{{colors.base0C_source.default.hex}}",
    base0D = "{{colors.base0D_source.default.hex}}",
    base0E = "{{colors.base0E_source.default.hex}}",
    base0F = "{{colors.base0F_source.default.hex}}",
}
