# Fish variables
# Generated by 'wal'
set -U wallpaper "{wallpaper}"

# Special
set -U background '{background}'
set -U foreground '{foreground}'
set -U cursor '{cursor}'

# Colors
set -U color0 '{color0}'
set -U color1 '{color1}'
set -U color2 '{color2}'
set -U color3 '{color3}'
set -U color4 '{color4}'
set -U color5 '{color5}'
set -U color6 '{color6}'
set -U color7 '{color7}'
set -U color8 '{color8}'
set -U color9 '{color9}'
set -U color10 '{color10}'
set -U color11 '{color11}'
set -U color12 '{color12}'
set -U color13 '{color13}'
set -U color14 '{color14}'
set -U color15 '{color15}'

# Shell colors
set -U fish_color_normal normal
set -U fish_color_command {color2.strip}
set -U fish_color_error {color1.strip}
set -U fish_color_param {foreground.strip}
set -U fish_color_quote {color2.strip}
set -U fish_color_autosuggestion {color8.strip}
set -U fish_color_escape {color3.strip}
set -U fish_color_operator $fish_color_escape
set -U fish_color_valid_path --underline
set -U fish_color_cwd green
set -U fish_pager_color_completion
set -U fish_pager_color_description $fish_color_quote yellow
set -U fish_pager_color_progress brwhite --background=cyan
set -U fish_color_history_current --bold
# # set fish_color_normal normal
# set fish_color_normal {foreground.strip}
# # set fish_color_command 005fd7
# set fish_color_command {color2.strip}
# # set fish_color_param 00afff
# set fish_color_param {color1.strip}
# # set fish_color_redirection 00afff
# set fish_color_redirection $fish_color_param
# # set fish_color_comment 990000
# set fish_color_comment {color8.strip}
# set fish_color_error ff0000
# # set fish_color_escape 00a6b2
# set fish_color_escape {color5.strip}
# # set fish_color_operator 00a6b2
# set fish_color_operator $fish_color_escape
# set fish_color_end {color4.strip}
# set fish_color_quote {color6.strip}
# set fish_color_autosuggestion 555 brblack
# set fish_color_user brgreen
# # set fish_color_host normal
# set fish_color_host $fish_color_normal
# set fish_color_valid_path --underline
# set fish_color_cwd green
# set fish_color_cwd_root red
# set fish_color_match --background=brblue
# set fish_color_search_match bryellow --background=brblack
# set fish_color_selection white --bold --background=brblack
# set fish_color_cancel -r
# set fish_pager_color_prefix white --bold --underline
# set fish_pager_color_completion
# # set fish_pager_color_description B3A06D yellow
# set fish_pager_color_description $fish_color_quote yellow
# set fish_pager_color_progress brwhite --background=cyan
# set fish_color_history_current --bold

# FZF colors
set -gx FZF_DEFAULT_OPTS "
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
