-- Auto-generated by Matugen

require("base16-colorscheme").setup({
    base00 = "#0e0e0e",
    base01 = "#1f1f1f",
    base02 = "#353535",
    base03 = "#474747",
    base04 = "#c6c6c6",
    base05 = "#e2e2e2",
    base06 = "#303030",
    base07 = "#393939",

    base08 = "#ffffff",
    base09 = "#ffb4ab",
    base0A = "#c6c6c6",
    base0B = "#919191",
    base0C = "#919191",
    base0D = "#d4d4d4",
    base0E = "#ababab",
    base0F = "#ffcbc5",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
    for _, v in pairs(groups) do
        vim.api.nvim_set_hl(0, v, value)
    end
end

set_hl_mutliple({ "TSFunction", "TSParameter" }, { link = "TSVariable" })
set_hl_mutliple({ "CursorLineSign", "CursorLineFold" }, { link = "CursorLine" })

vim.api.nvim_set_hl(0, "LineNr", { fg = "#919191" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#c6c6c6" })
