shell = "bash -c '{}'"

[[items]]
file = "~/.cache/flavours/colors.css"
template = "css"
rewrite = true

[[items]]
file = "~/.cache/flavours/colors-gtk.css"
template = "css"
subtemplate = "gtk-css"
rewrite = true

[[items]]
file = "~/.cache/flavours/colors.rasi"
template = "css"
subtemplate = "rasi"
rewrite = true

[[items]]
file = "~/.cache/flavours/colors-kitty.conf"
template = "conf"
subtemplate = "kitty"
rewrite = true

[[items]]
file = "~/.cache/flavours/colors-hypr.conf"
template = "conf"
subtemplate = "hypr"
rewrite = true

[[items]]
file = "~/.cache/flavours/colors.lua"
template = "lua"
rewrite = true

[[items]]
file = "~/.cache/flavours/colors-fuzzel.ini"
template = "ini"
subtemplate = "fuzzel"
rewrite = true
